# Generated by Django 5.0.6 on 2024-07-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categari',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategari',
            field=models.CharField(default='', max_length=60),
        ),
    ]
