# Generated by Django 5.0.6 on 2024-07-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msc', '0002_product_categari_product_price_product_subcategari'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='msc/images', upload_to=''),
        ),
    ]
