# Generated by Django 5.0.6 on 2024-07-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msc', '0004_contact_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='emails',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phno',
            new_name='phnos',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='des',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.AddField(
            model_name='contact',
            name='dess',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='contact',
            name='names',
            field=models.CharField(default='', max_length=30),
        ),
    ]
