# Generated by Django 5.0.6 on 2024-07-27 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msc', '0005_rename_email_contact_emails_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='dess',
            new_name='des',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='emails',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='names',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phnos',
            new_name='phno',
        ),
    ]
