# Generated by Django 5.0.6 on 2024-07-27 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msc', '0006_rename_dess_contact_des_rename_emails_contact_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
    ]
