# Generated by Django 5.0.6 on 2024-07-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msc', '0007_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30)),
                ('email', models.CharField(default='', max_length=60)),
                ('phno', models.CharField(default='', max_length=60)),
                ('des', models.CharField(default='', max_length=600)),
            ],
        ),
    ]
