# Generated by Django 5.0.6 on 2024-07-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msc', '0008_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phno',
            field=models.IntegerField(default='', max_length=60),
        ),
    ]
